POST http://localhost:19000/auth/register
Content-Type: application/json

{
  "name" : "Pau",
  "password" : "Pau12345678",
  "email" : "pau@gmail.com",
  "date_of_sign_up" : "2022-11-05",
  "RoleIdRole" : "Admin"
}

POST http://localhost:19000/auth/login
Content-Type: application/json

{
  "email" : "abel@gmail.com",
  "password" : "Abel1234"
}

