GET http://localhost:4113/users/mara.scampini@gmail.com
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiZWxAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2Njc2NzIwMDZ9.3uH6vYaYj7ZB9IA4dMRDKUMUoWD1MbWyVV9MXch5Kqk

PATCH http://localhost:19000/users/abel1@gmail.com
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiZWwxQGdtYWlsLmNvbSIsImlkIjoyLCJyb2xlIjoidXNlciIsImlhdCI6MTY2NzczODY0Nn0.jFBgQ17PaQligfw9dJ89x9ZqcQTtJH79kcQBeV_htVo
Content-Type: application/json

{
  "email": "abel@gmail.com"
}

